name: fitsaw
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  audioplayers: ^5.1.0
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  realm: ^1.5.0
  mongo_dart: ^0.9.3
  envied: ^0.3.0+3
  crypto: ^3.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: FitsawIcons
      fonts:
        - asset: assets/fonts/Fitsaw.ttf

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
